# -*- coding: utf-8 -*-
"""Descriptive Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1T_cgvR6h5vNH-Tib-tEVCByphSy7x_ZV
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
#total_distance=sum()
df=pd.read_csv("/content/Activity.csv")
df.info()
plt.bar(df['Total_Distance'],df['Calories_Burned'])
plt.xlabel("Distance")
plt.ylabel("calories burned")
plt.title("Fitness analysis")
plt.show()

plt.scatter(df['Total_Distance'], df['Calories_Burned'])
plt.xlabel("Distance")
plt.ylabel("Calories Burned")
plt.title("Distance vs Calories")
plt.show()

plt.boxplot(df['Calories_Burned'])
plt.title("Boxplot of Calories")
plt.show()

df.describe()

df[['Very_Active_Minutes',
    'Fairly_Active_Minutes']].plot.area()

plt.title("Activity Area Chart")
plt.show()

import seaborn as sns
corr = df.corr(numeric_only=True)

sns.heatmap(corr, annot=True)

plt.title("Correlation Heatmap")
plt.show()