# -*- coding: utf-8 -*-
"""Diagnostic Analysis2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1taPhGN0tTPg7RWLpfMB6DIqYwkBMWop-
"""

import pandas as pd
import numpy as np
import statistics
import matplotlib.pyplot as plt
import seaborn as sns
name=["Haniya","Aneesha","Ishaan","Harika","Bob"]
internet_speed=[3,5,4,7,6] #mbps
payment_failure=[2,1,0,2,1]
delivery_charges=[20,40,30,10,30]
purchase_completed=[False,True,True,False,True]
print("Dataset loaded suscessfully")
print("--customer Dataset--")
for i in range(len(name)):
  print(name[i],internet_speed[i],payment_failure[i],delivery_charges[i],purchase_completed[i])
#Total abandnment
total_abandment=purchase_completed.count(False)
print("Total abandments=",total_abandment)
#Internet diagnosis
for i in range(len(name)):
  if internet_speed[i]<5:
      print(name[i],internet_speed[i],"->reason for abandment")
  else:
    print(name[i],internet_speed[i],"->Not a reason for abandment")
#payment diagnosis
for i in range(len(name)):
  if payment_failure[i]==0:
    print(name[i],"->no payment issue")
  elif payment_failure[i]==1:
    print(name[i],"->minor payment issue")
  else:
    print(name[i],"->payment issue")
#delivery diagnosis
for i in range(len(name)):
  if delivery_charges[i]>=30:
    print(name[i],"->Reason for abandment")
  else:
    print(name[i],"->Not a reason for abandment")
#Root cause
print("\n-- Root cause---")
for i in range(len(name)):
  if purchase_completed[i]==False:
    if internet_speed[i]<5:
      print(name[i],"reason for internet diagnosis")
    elif payment_failure[i]>0:
      print(name[i],"reason for payment failure")
    elif delivery_charges[i]>30:
      print(name[i],"reason for abandment")
  #statistical analysis
  average_speed=sum(internet_speed)/len(internet_speed)
  print("Average internet speed=",average_speed)

plt.bar(name,delivery_charges)
plt.xlabel("name")
plt.ylabel("charges")
plt.title("Analsis")
plt.show()

