# -*- coding: utf-8 -*-
"""Fitness Data Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1r4mQtoER3MFJfYEdEkE-OTa1TXqhS8VN
"""

import statistics
names=["Haseena","Haniya","ishaan","Aneesha","safiya","Zainab"]
age=[45,34,23,32,36,20]
workout_hours=[4,6,2,3,5,1]
calories_burn=[200,400,600,800,500,250]

print("-----fitness center dataset----")
for i in range(len(names)):
  print(names[i],
        age[i],
        workout_hours[i],
        calories_burn[i])
#Average
average_workout_hours=sum(workout_hours)/len(workout_hours)
print("Average workout hours=",average_workout_hours)
#Highest calories burned
highest_calories=max(calories_burn)
print("Highest calories burned=",highest_calories)
#lowest workout
lowest_workout=min(workout_hours)
print("Lowest workout hours=",lowest_workout)
#Median
median_calories=statistics.median(calories_burn)
print("Median calories=",median_calories)
#Standard deviation
std_dev=statistics.stdev(calories_burn)
print("standard deviation=",std_dev)
#most active member
index=calories_burn.index(highest_calories)
print("Most active member=",names[index])
#Add Visualization
import matplotlib.pyplot as plt
plt.bar(names,calories_burn)
plt.scatter(names,calories_burn)

plt.xlabel("Members")
plt.ylabel("calories burned")
plt.title("Fitness analysis")
plt.show()