# -*- coding: utf-8 -*-
"""Food delivery analysis example.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RYH8jrHUOQFiE9jE2Q8rgxSwwlzM-Wgp
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
order_time=[3,4,2,3,1]
delivery_time=[20,30,35,45,35]
areas=["A","B","A","C","B"]
delivery_partner=["aneesha","haniya","aneesha","ishaan","haniya"]
customer_ratings=[3.4,5,4.5,3.8,4.5]
#df=pd.DataFrame({'Order_time':order_time,'Delivery_time':delivery_time,'Delivery_partner':delivery_partner,'Customer_ratings':customer_ratings})
#print(df)
#average_delivery_time=df['Delivery_time'].mean()
#print("Average delivery time=",average_delivery_time)
#average delivery time
average_delivery_time=sum(delivery_time)/len(delivery_time)
print("Average delivery time=",average_delivery_time)
#peak order hours
#order_hours=df.groupby('Delivery_partner')['Order_time'].sum()
#peak_order_hours=order_hours.max()
#print("peak order hours=",peak_order_hours)
#most delayed areas
max_time=max(delivery_time)
index=delivery_time.index(max_time)
print("most delayed area:",areas[index])
#top rated delivery partners
max_ratings=max(customer_ratings)
index=customer_ratings.index(max_ratings)
print("Top rated delivery partner:",delivery_partner[index])
#peak order hours
peak_order_hours=max(order_time)
print("peak order hours:",peak_order_hours)

plt.figure(figsize=(5,3))
plt.bar(order_time,delivery_time)
plt.xlabel('order_time')
plt.ylabel('delivery time')
plt.title("order time vs delivery time")
plt.show()

plt.figure(figsize=(8,5))
plt.pie(customer_ratings, autopct='%1.1f%%')
plt.title('customer Ratings')
plt.show()

from collections import Counter

area_counts = Counter(areas)
labels = list(area_counts.keys())
sizes = list(area_counts.values())

plt.figure(figsize=(8,5))
plt.pie(sizes, labels=labels, autopct='%1.1f%%', startangle=90)
plt.title('Distribution of Areas')
plt.axis('equal') # Equal aspect ratio ensures that pie is drawn as a circle.
plt.show()

print("---recommendations---")
print("Assign more delivery partners during peak hours")
print("Delivery time have to be minimized by assigning more partners")

