# -*- coding: utf-8 -*-
"""fraud transactions analysis example.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AGRqb2PSyqDWmqXbKsPgj9nTRp5DvKKN
"""

import pandas as pd
import numpy as p
import matplotlib.pyplot as plt
import seaborn as sns
transaction_amount=[2873.87,14000,6321.23,9000,2176.12,34022,1203]
location=["Hyderabad","Madanapalle","Galiveedu","Banglore","Pune","Kerala"]
accounts=["Aneesha","Haniya","Ishaan","Safiya","Harika","Sameera"]
times=[2,18,13,23,4,9]
account_activity=[2,5,3,3,1,6,1]
#unusual transactions
for i in range(len(transaction_amount)):
    if transaction_amount[i]>10000:
        print("Unsual transactions:",transaction_amount[i])
#high risk accounts
for i in range(len(account_activity)):
    if account_activity[i]>4:
        print("High risk accounts:",accounts[i])
#fraud patterns
for i in range(len(times)):
   if(times[i]>22 or times[i]<5):
       print("fraud transaction account:",accounts[i])

transaction_amount = transaction_amount[:-1]

plt.figure(figsize=(5,5))
transaction_amount = transaction_amount[:len(accounts)]
sns.barplot(x=accounts,y=transaction_amount)
plt.show()

plt.figure(figsize=(5,5))
plt.pie(transaction_amount,labels=accounts,autopct="%1.2f%%")
plt.show()

plt.figure(figsize=(7,5))
sns.barplot(x=location,y=transaction_amount)
plt.show()