# -*- coding: utf-8 -*-
"""online shopping customer analysis example.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mC5_p3REDxrTtpQCYDx45FbtVBXHmh9Q
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
#dataset
product_purchases=["electronics","grocery","electronics","stationary","electronics","clothing","grocery"]
cart_abandonment=["grocery","clothing"]
customer_ratings=[4.5,3.0,3.5,5.0,4.8]
payment_methods=["UPI","credit","debit","COD","bank","QR CODE","wallets","UPI","COD","UPI","COD","bank","COD"]
#most sold products
most_sold_products=max(product_purchases,key=product_purchases.count)
print("Most sold products:",most_sold_products)
#high revenue customers
customers=["A","B","C","A","B"]
amount=[1000,900,1000,2000,300]
A=0
B=0
C=0
for i in range(len(customers)):
  if(customers[i]=="A"):
    A=A+amount[i]
  elif(customers[i]=="B"):
    B=B+amount[i]
  elif(customers[i]=="C"):
    C=C+amount[i]
print("A:",A)
print("B:",B)
print("C:",C)
if(A>B and A>C):
  print("Highest revenue customer is:",A)
elif(B>C and B>C):
  print("Highest revenue customer is:",B)
else:
  print("Highest reveue customer is:",C)
#most popular payment method
most_popular_payment_method=max(payment_methods,key=payment_methods.count)
print("Most popular payment method:",most_popular_payment_method)
#products with poor ratings
poor_ratings=min(customer_ratings)
index=customer_ratings.index(poor_ratings)
print("Top rated delivery partner:",customers[index])

plt.figure(figsize=(5,5))
product_counts = pd.Series(product_purchases).value_counts()
plt.pie(product_counts, labels=product_counts.index, autopct='%1.1f%%', startangle=90)
plt.title("Most sold products")
plt.show()

plt.figure(figsize=(5,3))
plt.bar(customers,amount)
plt.title("Highest revenue customers")
plt.xlabel("Customers")
plt.ylabel("Amount")
plt.title("Highest revenue customers")
plt.show()

plt.figure(figsize=(5,5))
payment_counts = pd.Series(payment_methods).value_counts()
plt.pie(payment_counts, labels=payment_counts.index, autopct='%1.1f%%', startangle=90)
plt.title("Most popular payment method")
plt.show()