# -*- coding: utf-8 -*-
"""predictive analysis1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iNXzmpNE1XdIfLTgK-xSXXfA3679pScQ
"""

water_consumption = [100, 150, 170, 180, 200]
days = [2, 4, 1, 2, 3]

# Average consumption
total = 0
for v in water_consumption:
    total += v
avg_consumption = total / len(water_consumption)

# Usage per day
usage_per_day = []
for i in range(len(water_consumption)):
    usage_per_day.append(water_consumption[i] / days[i])

total_usage = 0
for v in usage_per_day:
    total_usage += v
total_usage_per_day_avg = total_usage / len(usage_per_day)

# Increase
increase = [0]
for i in range(1, len(water_consumption)):
    increase.append(water_consumption[i] - water_consumption[i - 1])

sum_increase = 0
for v in increase:
    sum_increase += v

# Shortage check
shortage_occurs = True
for i in range(1, len(water_consumption)):
    if water_consumption[i] < water_consumption[i - 1]:
        shortage_occurs = False
        break
print("Average Consumption:", avg_consumption)
print("Avg Usage per Day:", total_usage_per_day_avg)
print("Sum of Increased Water:", sum_increase)
print("Shortage Occurs:", shortage_occurs)