# -*- coding: utf-8 -*-
"""predictive analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Fma93yS7w_eAZLgx7ze-GynQtY8Uc8o1
"""

import pandas as pd
import numpy as np
import statistics
import matplotlib.pyplot as plt
import seaborn as sns
# Dataset
water_consumption = [100, 150, 170, 180, 200]
days = [2, 4, 1, 2, 3]

df = pd.DataFrame({
    "Water_Consumption": water_consumption,
    "Days": days
})

#  Average water consumption
avg_consumption = df["Water_Consumption"].mean()

# Total water usage per day
df["Usage_per_Day"] = df["Water_Consumption"] / df["Days"]
total_usage_per_day_avg = df["Usage_per_Day"].mean()

#  Water usage increased
df["Increase"] = df["Water_Consumption"].diff()

# Sum of daily increased water
sum_increase = df["Increase"].sum()

# Shortage condition
shortage_occurs = df["Water_Consumption"].is_monotonic_increasing

print(df)
print("Average Consumption:", avg_consumption)
print("Avg Usage per Day:", total_usage_per_day_avg)
print("Sum of Increased Water:", sum_increase)
print("Shortage Occurs:", shortage_occurs)

plt.bar(water_consumption,days)
plt.xlabel("Water consumption")
plt.ylabel("Days")
plt.title("Analysis")
plt.show()

