# -*- coding: utf-8 -*-
"""prescriptive analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Qz95wa0o74zoNWsBHIBlqbBhmHNVfRPy
"""

import pandas as pd
import numpy as np
patient_name=["Aneesha","Harika","Haniya","Ishaan","Safiya"]
age=[22,20,12,6,34]
condition=["medium","normal","medium","critical","normal"]
oxygen_level=[45,40,34,40,23,67]
available_beds=4
for i in range(len(patient_name)):
  print(patient_name[i],age[i],condition[i],oxygen_level[i])
priority_scores = []
prescriptions = []
# Priority Score Calculation
for i in range(len(patient_name)):
    score = 0
    # Condition score
    if condition[i] == "critical":
        score += 50
    elif condition[i] == "medium":
        score += 30
    else:
        score += 10
    # Oxygen level score
    if oxygen_level[i] < 30:
        score += 40
    elif oxygen_level[i] < 40:
        score += 25
    else:
        score += 10
    # Age score
    if age[i] < 12 and oxygen_level[i]<=40:
        score += 20
    priority_scores.append(score)

    # Prescription
    if condition[i] == "critical":
        prescriptions.append("ICU Care + Oxygen Support")
    elif condition[i] == "medium":
        prescriptions.append("Oxygen Therapy + Monitoring")
    else:
        prescriptions.append("General Medication")

# Sorting patients based on priority
sorted_index = np.argsort(priority_scores)[::-1]

# Bed Allocation
bed_allocated = ["No"] * len(patient_name)

for i in range(available_beds):
    bed_allocated[sorted_index[i]] = "Yes"

# Final Output
print("Patient Details:\n")

for i in sorted_index:
    print("Name :", patient_name[i])
    print("Age :", age[i])
    print("Condition :", condition[i])
    print("Oxygen Level :", oxygen_level[i])
    print("Priority Score :", priority_scores[i])
    print("Bed Allocated :", bed_allocated[i])
    print("Prescription :", prescriptions[i])

