# -*- coding: utf-8 -*-
"""Statistical Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16hAfHr_Mu7jPqEPZy3fn00hNEnFZ9AfH
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy import stats
marks=[20,30,40,50,90]
hours=[4,5,6,4,9]
print("Mean:",np.mean(marks))
print("Meadian:",np.median(marks))
print("Mode:",stats.mode(marks).mode)
print("variance:",np.var(marks))
print("Standard deviation:",np.std(marks))
print("Standard deviation:",np.std(marks))
print("correlation:",np.corrcoef(marks))

plt.figure()